version: '3.7'

services:
  letsencrypt:
    image: adferrand/dnsrobocert:latest
    container_name: letsencrypt-dns
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/etc/letsencrypt
      - ./le-config.yml:/etc/dnsrobocert/config.yml
    restart: always
  sish:
    image: antoniomika/sish:latest
    container_name: sish
    depends_on: 
      - letsencrypt
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./pubkeys:/pubkeys
      - ./keys:/keys
      - ./ssl:/ssl
    command: |
      --ssh-address=:2222
      --domain=fibona.cc
      --http-address=:80
      --https-address=:443
      --https=true
      --https-certificate-directory=/ssl
      --private-keys-directory=/keys
      --bind-random-ports=false
      --authentication=false
      --bind-hosts=fibona.cc
      --bind-random-subdomains=false
      --idle-connection=false
    network_mode: host
    restart: always
